# Generated by Django 3.0.4 on 2020-05-25 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recreation', '0001_initial'),
        ('artifacts', '0003_auto_20200507_0047'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='recreationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.Recreation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='artifactID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artifacts.Artifact'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('userID', 'artifactID', 'recreationID')},
        ),
    ]
