# Generated by Django 3.0.4 on 2020-06-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactRecreation',
            fields=[
                ('recreationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='artifact_recreate', serialize=False, to='artifacts.Artifact')),
                ('artifactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.Artifact')),
            ],
        ),
    ]
