# Generated by Django 3.0.4 on 2020-06-02 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recreation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreation',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recreationimage',
            name='predict',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='recreationimage',
            name='tendency',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='recreation',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recreation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recreationimage',
            name='recreationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recreation_image', to='recreation.Recreation'),
        ),
    ]
