export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const FIRSTDRAWER_OPEN = 'FIRSTDRAWER_OPEN';
export const LOGINDRAWER_OPEN = 'LOGINDRAWER_OPEN';
export const SIGNUPDRAWER_OPEN = 'SIGNUPDRAWER_OPEN';