# Generated by Django 3.0.4 on 2020-04-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200419_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='userID',
        ),
    ]
