# Generated by Django 3.0.4 on 2020-05-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0001_initial'),
        ('comment', '0004_auto_20200420_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recreationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recreation.Recreation'),
        ),
    ]
