# Generated by Django 3.0.4 on 2020-05-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_auto_20200507_0047'),
        ('comment', '0005_comment_recreationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='artifactID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artifacts.Artifact'),
        ),
    ]
