# Generated by Django 3.0.6 on 2020-06-02 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now=True)),
                ('recreateFlag', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('predict', models.IntegerField(default=-1)),
                ('tendency', jsonfield.fields.JSONField(null=True)),
                ('artifactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_image', to='artifacts.Artifact')),
            ],
        ),
    ]
