# Generated by Django 3.0.6 on 2020-06-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_auto_20200607_1748'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artifact',
            table='artifact',
        ),
    ]
