# Generated by Django 3.0.6 on 2020-05-19 02:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_auto_20200507_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactimage',
            name='predict',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='artifactimage',
            name='tendency',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
