# Generated by Django 3.0.6 on 2020-06-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_auto_20200607_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='recreatation',
            new_name='recreation',
        ),
        migrations.AlterModelTable(
            name='artifact',
            table=None,
        ),
    ]
