# Generated by Django 3.0.6 on 2020-05-25 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artifacts', '0004_auto_20200519_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artifactimage',
            name='artifactId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_image', to='artifacts.Artifact'),
        ),
    ]
