# Generated by Django 3.0.4 on 2020-06-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='artifactID',
            new_name='imageID',
        ),
    ]
