# Generated by Django 3.0.4 on 2020-06-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        ('purchase_check', '0002_auto_20200615_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='imageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artifacts.ArtifactImage'),
        ),
    ]
